package com.lidetao.dao.po;

public class WikiBlock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.id
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.theme
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.file
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String file;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.area
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String area;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.areaorder
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private Byte areaorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String block;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.fun
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String fun;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.tpl
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String tpl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.modified
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private Integer modified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wiki_block.params
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    private String params;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.id
     *
     * @return the value of wiki_block.id
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.id
     *
     * @param id the value for wiki_block.id
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.theme
     *
     * @return the value of wiki_block.theme
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.theme
     *
     * @param theme the value for wiki_block.theme
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.file
     *
     * @return the value of wiki_block.file
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.file
     *
     * @param file the value for wiki_block.file
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.area
     *
     * @return the value of wiki_block.area
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.area
     *
     * @param area the value for wiki_block.area
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.areaorder
     *
     * @return the value of wiki_block.areaorder
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public Byte getAreaorder() {
        return areaorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.areaorder
     *
     * @param areaorder the value for wiki_block.areaorder
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setAreaorder(Byte areaorder) {
        this.areaorder = areaorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.block
     *
     * @return the value of wiki_block.block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getBlock() {
        return block;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.block
     *
     * @param block the value for wiki_block.block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setBlock(String block) {
        this.block = block == null ? null : block.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.fun
     *
     * @return the value of wiki_block.fun
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getFun() {
        return fun;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.fun
     *
     * @param fun the value for wiki_block.fun
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setFun(String fun) {
        this.fun = fun == null ? null : fun.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.tpl
     *
     * @return the value of wiki_block.tpl
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getTpl() {
        return tpl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.tpl
     *
     * @param tpl the value for wiki_block.tpl
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setTpl(String tpl) {
        this.tpl = tpl == null ? null : tpl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.modified
     *
     * @return the value of wiki_block.modified
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public Integer getModified() {
        return modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.modified
     *
     * @param modified the value for wiki_block.modified
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setModified(Integer modified) {
        this.modified = modified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wiki_block.params
     *
     * @return the value of wiki_block.params
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wiki_block.params
     *
     * @param params the value for wiki_block.params
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    public void setParams(String params) {
        this.params = params == null ? null : params.trim();
    }
}