package com.lidetao.dao;

import com.lidetao.dao.po.WikiBlock;
import com.lidetao.dao.po.WikiBlockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WikiBlockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int countByExample(WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int deleteByExample(WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int insert(WikiBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int insertSelective(WikiBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    List<WikiBlock> selectByExampleWithBLOBs(WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    List<WikiBlock> selectByExample(WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    WikiBlock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int updateByExampleSelective(@Param("record") WikiBlock record, @Param("example") WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WikiBlock record, @Param("example") WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int updateByExample(@Param("record") WikiBlock record, @Param("example") WikiBlockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int updateByPrimaryKeySelective(WikiBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WikiBlock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wiki_block
     *
     * @mbggenerated Sun Mar 12 13:31:40 CST 2017
     */
    int updateByPrimaryKey(WikiBlock record);
}